# Exception to log on backtest results page
class Backtest_Exception(Exception):
    pass
